# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=225)),
                ('address', models.TextField()),
                ('town', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('status', models.CharField(max_length=225)),
                ('listing_type', models.CharField(max_length=225)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
