# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='ordering',
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('apartments', 'APARTMENTS'), ('houses', 'HOUSES'), ('studios', 'STUDIOS'), ('commercial', 'COMMERCIAL')], default='Property Type', max_length=25),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('for sale', 'For Sale'), ('for rent', 'For Rent')], default='Property Status', max_length=25),
        ),
    ]
