# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20171118_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='features',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('apartments', 'Apartments'), ('houses', 'Houses'), ('studios', 'Studios'), ('commercial', 'Commercial')], default='Property Type', max_length=25),
        ),
    ]
