# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bathroom',
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
